GET http://localhost:8080/api/flower/list/

###
POST http://localhost:8080/api/flower/add/
Content-Type: application/json

{
"id":1,
"sepalLength":0.8,
"color":"BLUE",
"price":45,
"flowerType":"TULIP"
}